from __future__ import annotations

from pathlib import Path
from typing import Any, cast

import numpy as np
from loguru import logger

from src.idf import IDF
from src.idf.models import BuildingSurfaceDetailed, FenestrationSurfaceDetailed

BUILDING_SURFACE_OBJECT_TYPE = 'BuildingSurface:Detailed'
FENESTRATION_SURFACE_OBJECT_TYPE = 'FenestrationSurface:Detailed'
WINDOW_SIZE = [1920, 1080]


def idf_render(idf: IDF, output_path: Path) -> None:
    """Render an IDF preview image with PyVista.

    Args:
        idf: IDF object container generated by converter.
        output_path: PNG output path.

    Raises:
        ImportError: If PyVista is not installed.
        ValueError: If no renderable polygons exist in the IDF.
    """
    try:
        import pyvista as pv
    except ImportError as e:  # pragma: no cover - runtime dependency guard
        raise ImportError(
            'PyVista is required for preview rendering. Install pyvista first.'
        ) from e

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    building_polygons = _collect_building_surface_polygons(idf)
    fenestration_polygons = _collect_fenestration_polygons(idf)

    if not building_polygons and not fenestration_polygons:
        raise ValueError('No renderable surfaces found in IDF')

    # PyVista stubs are incomplete; use Any to keep static checking stable.
    pv_any: Any = pv
    plotter: Any = pv_any.Plotter(off_screen=True, window_size=WINDOW_SIZE)

    try:
        cast(Any, plotter.set_background)('white')

        building_mesh = _build_polydata(building_polygons, pv_any)
        if building_mesh is not None:
            plotter.add_mesh(
                building_mesh,
                color='#d9d9d9',
                opacity=0.9,
                show_edges=False,
                smooth_shading=True,
            )

        fenestration_mesh = _build_polydata(fenestration_polygons, pv_any)
        if fenestration_mesh is not None:
            plotter.add_mesh(
                fenestration_mesh,
                color='#4a90e2',
                opacity=1.0,
                show_edges=False,
                smooth_shading=True,
            )

        cast(Any, plotter.view_isometric)()
        cast(Any, plotter.reset_camera)()
        plotter.screenshot(str(output_path))
    finally:
        plotter.close()

    logger.info(f'Generated IDF preview image: {output_path}')


def _collect_building_surface_polygons(idf: IDF) -> list[np.ndarray]:
    polygons: list[np.ndarray] = []
    building_surfaces = idf.all_of_type(BUILDING_SURFACE_OBJECT_TYPE).values()

    for surface in building_surfaces:
        if not isinstance(surface, BuildingSurfaceDetailed):
            continue

        vertices = surface.vertices
        if not vertices:
            logger.debug(f'Skipping {surface.name}: no vertices')
            continue

        polygon = np.array(
            [
                [
                    vertex.vertex_x_coordinate,
                    vertex.vertex_y_coordinate,
                    vertex.vertex_z_coordinate,
                ]
                for vertex in vertices
            ],
            dtype=float,
        )
        normalized_polygon = _normalize_polygon(polygon)
        if normalized_polygon is None:
            logger.warning(f'Skipping {surface.name}: invalid polygon')
            continue

        polygons.append(normalized_polygon)

    return polygons


def _collect_fenestration_polygons(idf: IDF) -> list[np.ndarray]:
    polygons: list[np.ndarray] = []
    fenestration_surfaces = idf.all_of_type(FENESTRATION_SURFACE_OBJECT_TYPE).values()

    for surface in fenestration_surfaces:
        if not isinstance(surface, FenestrationSurfaceDetailed):
            continue

        points = [
            [
                float(surface.vertex_1_x_coordinate),
                float(surface.vertex_1_y_coordinate),
                float(surface.vertex_1_z_coordinate),
            ],
            [
                float(surface.vertex_2_x_coordinate),
                float(surface.vertex_2_y_coordinate),
                float(surface.vertex_2_z_coordinate),
            ],
            [
                float(surface.vertex_3_x_coordinate),
                float(surface.vertex_3_y_coordinate),
                float(surface.vertex_3_z_coordinate),
            ],
        ]

        optional_vertex = (
            surface.vertex_4_x_coordinate,
            surface.vertex_4_y_coordinate,
            surface.vertex_4_z_coordinate,
        )
        if all(value is not None for value in optional_vertex):
            vertex_4_x, vertex_4_y, vertex_4_z = optional_vertex
            assert vertex_4_x is not None
            assert vertex_4_y is not None
            assert vertex_4_z is not None
            points.append([float(vertex_4_x), float(vertex_4_y), float(vertex_4_z)])
        elif any(value is not None for value in optional_vertex):
            logger.warning(f'Skipping {surface.name}: incomplete 4th vertex')
            continue

        polygon = np.array(points, dtype=float)
        normalized_polygon = _normalize_polygon(polygon)
        if normalized_polygon is None:
            logger.warning(f'Skipping {surface.name}: invalid polygon')
            continue

        polygons.append(normalized_polygon)

    return polygons


def _normalize_polygon(points: np.ndarray) -> np.ndarray | None:
    if points.ndim != 2 or points.shape[1] != 3:
        return None

    if len(points) >= 2 and np.allclose(points[0], points[-1]):
        points = points[:-1]

    if len(points) < 3:
        return None

    return points


def _build_polydata(polygons: list[np.ndarray], pv: Any):
    if not polygons:
        return None

    points = np.vstack(polygons)

    faces: list[int] = []
    offset = 0
    for polygon in polygons:
        vertex_count = polygon.shape[0]
        faces.extend([vertex_count, *range(offset, offset + vertex_count)])
        offset += vertex_count

    return pv.PolyData(points, np.array(faces, dtype=np.int64))
