from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, cast

import numpy as np
from loguru import logger

from src.idf import IDF
from src.idf.models import BuildingSurfaceDetailed, FenestrationSurfaceDetailed

WINDOW_SIZE = [1920, 1080]


@dataclass
class SurfaceStyle:
    color: str
    opacity: float


SURFACE_STYLES: dict[str, SurfaceStyle] = {
    'Roof': SurfaceStyle(color='#993333', opacity=1.0),
    'Ceiling': SurfaceStyle(color='#993333', opacity=1.0),
    'Wall': SurfaceStyle(color='#C8B44C', opacity=1.0),
    'Floor': SurfaceStyle(color='#808080', opacity=1.0),
}
WINDOW_STYLE = SurfaceStyle(color='#66C0E0', opacity=0.6)


@dataclass
class SurfaceGroup:
    style: SurfaceStyle
    polygons: list[np.ndarray] = field(default_factory=list)


def idf_render(idf: IDF, output_path: Path) -> None:
    """Render an IDF preview image with PyVista.

    Args:
        idf: IDF object container generated by converter.
        output_path: PNG output path.

    Raises:
        ImportError: If PyVista is not installed.
        ValueError: If no renderable polygons exist in the IDF.
    """
    try:
        import pyvista as pv
    except ImportError as e:  # pragma: no cover - runtime dependency guard
        raise ImportError(
            'PyVista is required for preview rendering. Install pyvista first.'
        ) from e

    output_path.parent.mkdir(parents=True, exist_ok=True)

    surface_groups = _collect_building_surface_groups(idf)
    window_group = SurfaceGroup(style=WINDOW_STYLE)
    window_group.polygons = _collect_fenestration_polygons(idf)

    has_any = window_group.polygons or any(g.polygons for g in surface_groups.values())
    if not has_any:
        raise ValueError('No renderable surfaces found in IDF')

    # PyVista stubs are incomplete; use Any to keep static checking stable.
    pv_any: Any = pv
    plotter: Any = pv_any.Plotter(off_screen=True, window_size=WINDOW_SIZE)

    try:
        cast(Any, plotter.set_background)('white')

        for group in surface_groups.values():
            mesh = _build_polydata(group.polygons, pv_any)
            if mesh is not None:
                plotter.add_mesh(
                    mesh,
                    color=group.style.color,
                    opacity=group.style.opacity,
                    show_edges=False,
                    smooth_shading=True,
                )

        window_mesh = _build_polydata(window_group.polygons, pv_any)
        if window_mesh is not None:
            plotter.add_mesh(
                window_mesh,
                color=WINDOW_STYLE.color,
                opacity=WINDOW_STYLE.opacity,
                show_edges=False,
                smooth_shading=True,
            )

        cast(Any, plotter.view_isometric)()
        cast(Any, plotter.reset_camera)()
        plotter.screenshot(str(output_path))
    finally:
        plotter.close()

    logger.info(f'Generated IDF preview image: {output_path}')


def _collect_building_surface_groups(idf: IDF) -> dict[str, SurfaceGroup]:
    groups: dict[str, SurfaceGroup] = {
        stype: SurfaceGroup(style=style) for stype, style in SURFACE_STYLES.items()
    }
    building_surfaces = idf.all_of_type(
        BuildingSurfaceDetailed._idf_object_type
    ).values()

    for surface in building_surfaces:
        if not isinstance(surface, BuildingSurfaceDetailed):
            continue

        vertices = surface.vertices
        if not vertices:
            logger.debug(f'Skipping {surface.name}: no vertices')
            continue

        polygon = np.array(
            [
                [
                    vertex.vertex_x_coordinate,
                    vertex.vertex_y_coordinate,
                    vertex.vertex_z_coordinate,
                ]
                for vertex in vertices
            ],
            dtype=float,
        )
        normalized_polygon = _normalize_polygon(polygon)
        if normalized_polygon is None:
            logger.warning(f'Skipping {surface.name}: invalid polygon')
            continue

        group = groups.get(surface.surface_type)
        if group is None:
            logger.debug(f'Unknown surface type: {surface.surface_type}')
            continue
        group.polygons.append(normalized_polygon)

    return groups


def _collect_fenestration_polygons(idf: IDF) -> list[np.ndarray]:
    polygons: list[np.ndarray] = []
    fenestration_surfaces = idf.all_of_type(
        FenestrationSurfaceDetailed._idf_object_type
    ).values()

    for surface in fenestration_surfaces:
        if not isinstance(surface, FenestrationSurfaceDetailed):
            continue

        points = [
            [
                float(surface.vertex_1_x_coordinate),
                float(surface.vertex_1_y_coordinate),
                float(surface.vertex_1_z_coordinate),
            ],
            [
                float(surface.vertex_2_x_coordinate),
                float(surface.vertex_2_y_coordinate),
                float(surface.vertex_2_z_coordinate),
            ],
            [
                float(surface.vertex_3_x_coordinate),
                float(surface.vertex_3_y_coordinate),
                float(surface.vertex_3_z_coordinate),
            ],
        ]

        vertex_4_x = surface.vertex_4_x_coordinate
        vertex_4_y = surface.vertex_4_y_coordinate
        vertex_4_z = surface.vertex_4_z_coordinate
        if vertex_4_x is not None and vertex_4_y is not None and vertex_4_z is not None:
            points.append([float(vertex_4_x), float(vertex_4_y), float(vertex_4_z)])
        elif any(v is not None for v in (vertex_4_x, vertex_4_y, vertex_4_z)):
            logger.warning(f'Skipping {surface.name}: incomplete 4th vertex')
            continue

        polygon = np.array(points, dtype=float)
        normalized_polygon = _normalize_polygon(polygon)
        if normalized_polygon is None:
            logger.warning(f'Skipping {surface.name}: invalid polygon')
            continue

        polygons.append(normalized_polygon)

    return polygons


def _normalize_polygon(points: np.ndarray) -> np.ndarray | None:
    if points.ndim != 2 or points.shape[1] != 3:
        return None

    if len(points) >= 2 and np.allclose(points[0], points[-1]):
        points = points[:-1]

    if len(points) < 3:
        return None

    return points


def _build_polydata(polygons: list[np.ndarray], pv: Any):
    if not polygons:
        return None

    points = np.vstack(polygons)

    faces: list[int] = []
    offset = 0
    for polygon in polygons:
        vertex_count = polygon.shape[0]
        faces.extend([vertex_count, *range(offset, offset + vertex_count)])
        offset += vertex_count

    return pv.PolyData(points, np.array(faces, dtype=np.int64))
